# こちらのリンクを参照：https://gist.github.com/harveyconnor/518e088bad23a273cae6ba7fc4643549
version: "3"
services:
  node:
    container_name: node
    build: node/.
    volumes: ["./node:/app", "/app/node_modules"]
    depends_on:
      - mongo-setup
    links:
      - "mongo1"
      - "mongo2"
      - "arbiter"
  mongo-setup:
    container_name: mongo-setup
    image: mongo
    restart: on-failure
    networks:
      default:
    volumes:
      - ./scripts:/scripts
    entrypoint: ["/scripts/setup.sh"]
    depends_on:
      - mongo1
      - mongo2
      - arbiter

  mongo1:
    hostname: mongo1
    container_name: localmongo1
    image: mongo
    expose:
      - 27017
    ports:
      - 27017:27017
    restart: always
    entrypoint:
      [
        "/usr/bin/mongod",
        "--bind_ip_all",
        "--replSet",
        "rs0",
        "--journal",
        "--dbpath",
        "/data/db",
        "--enableMajorityReadConcern",
        "false",
        "--quiet",
        "--logpath",
        "/dev/null",
      ]

  mongo2:
    hostname: mongo2
    container_name: localmongo2
    image: mongo
    expose:
      - 27017
    ports:
      - 27018:27017
    restart: always
    entrypoint:
      [
        "/usr/bin/mongod",
        "--bind_ip_all",
        "--replSet",
        "rs0",
        "--journal",
        "--dbpath",
        "/data/db",
        "--enableMajorityReadConcern",
        "false",
        "--quiet",
        "--logpath",
        "/dev/null",
      ]

  arbiter:
    hostname: arbiter
    container_name: arbiter
    image: mongo
    expose:
      - 27017
    ports:
      - 27019:27017
    restart: always
    entrypoint:
      [
        "/usr/bin/mongod",
        "--bind_ip_all",
        "--replSet",
        "rs0",
        "--journal",
        "--dbpath",
        "/data/db",
        "--enableMajorityReadConcern",
        "false",
        "--quiet",
        "--logpath",
        "/dev/null",
      ]
